language: generic
    
before_install:
 - wget https://github.com/CapsAdmin/goluwa/archive/master.zip && unzip master.zip -d ../goluwa
 
script:
 - |
    paths=($(git -C $TRAVIS_BUILD_DIR diff --name-only $TRAVIS_COMMIT_RANGE))
    echo $paths
    paths=("${paths[@]/#/$TRAVIS_BUILD_DIR/}")
    bash ../goluwa/goluwa-master/goluwa cli --gluacheck $(printf '"%s" ' "${paths[@]}")
